### ISSUE TITLE
Load the table autoAdmin.exemptionList from own file?

### ISSUE THREAD

**Issue by HubJack** [mrSkortch/DCS-SLmod#13]
Regarding autoAdmin.exemptionList in config.lua

Can we change this function to read from a separate file, like the BANLIST? We have so many members that the config file becomes too long. I think this will simplify the Squadron member white-listing from KICK and BAN. Some of our players get kicked in training sessions where we test players in danger close situations.

**Comment by mrSkortch** [comment]
Doesn't sound to difficult to implement.

**Comment by mrSkortch** [comment]
Should be implemented now with: https://github.com/mrSkortch/DCS-SLmod/commit/e08caa60d667b769dda81e960450b6e2e5626e22
