### ISSUE TITLE
Message from admins coming up as radio message in upper right corner

### ISSUE THREAD

**Issue by baluballa** [mrSkortch/DCS-SLmod#14]
Sometimes people fly without chat window open. Would be nice if an Admin could type a message in chat window that comes up as a _message to all_. Eg -admin say to all "Server is going to restart in xx mins".

**Comment by mrSkortch** [comment]
Looking into it.

**Comment by mrSkortch** [comment]
Added with commit: https://github.com/mrSkortch/DCS-SLmod/commit/bfc3ae7c1234ba5906ba0cfcf6dcf3df39d5dafc
