### ISSUE TITLE
RTV/Vote Mission

### ISSUE THREAD

**Issue by mrSkortch** [mrSkortch/DCS-SLmod#18]
Mechanism for players to vote for a mission change.

Design: Players can call for a vote via -rtv command (rock the vote). Once threshold reached a vote can start. 

Possible ideas.
Players nominate missions
Players nominate a map
Admin command to cancel a vote
Admin command to enable/disable voting in session
Vote threashold settings.

**Comment by bigmillertime** [comment]
This would be amazing! Do you have any progress made?

**Comment by bigmillertime** [comment]
Right on, sir. Thanks so much for your hard work!

**Comment by mrSkortch** [comment]
Closing this since its live and there havent been any complaints of it being broken.
