### ISSUE TITLE
Slmod Still working on dcs?

### ISSUE THREAD

**Issue by Enfarda** [mrSkortch/DCS-SLmod#27]
All this time the SLmod was always working, but afther today is not anymore, is because of some update, or i need reinstall this?

**Comment by mrSkortch** [comment]
Should be working. Check your DCS.log and make sure that there is a line with: 

SlmodTests.lua loaded

and then when starting a server there is a:

 LuaNET: SLMOD INFO: successfully completed slmod.getMissionUnitData()

that should be the last line that slmod does while it loads

**Comment by Enfarda** [comment]
Forget it was working... my mistake i mess up in one thing only, sorry for something.
stay well and i hope you think about request ^^
