### ISSUE TITLE
Mission Script Error

### ISSUE THREAD

**Issue by G510Gamer** [mrSkortch/DCS-SLmod#29]
```
[string 'slmod.sendData()':1: attempt to index global 'slmod' (a nil value)
stack traceback:
    [C]: ?
    [string "slmod.sendData()"]1: in main chunk
```

i dunno what it means but its popping up whenever i try to host

**Comment by mrSkortch** [comment]
Check your DCS.log to see if it has the following errors. If so you need to launch the game as admin. 

00006.349 INFO LuaNET: SLMOD WARNING: ./Scripts/MissionScripting.lua is not up to date. Installing new ./Scripts/MissionScripting.lua.
00006.349 ERROR VFS: VFS_open_write: CreateFile(./Scripts/MissionScripting.lua): Access is denied.
00006.349 INFO LuaNET: SLMOD ERROR: Unable to open ./Scripts/MissionScripting.lua for writing, reason: can't open "./Scripts/MissionScripting.lua" for 'w'

**Comment by G510Gamer** [comment]
Found out why DCS want running in admin mode. 
thanks for the help
