### ISSUE TITLE
Feature Request: Make MOTD not display for users on a list

### ISSUE THREAD

**Issue by eoovipaul** [mrSkortch/DCS-SLmod#37]
Our server is open to the public as well as clan members,
would like not to display the MOTD for our clan members (they already know the score with our server config - SLMOD)
But for public people it would be useful to let them know about SLMOD - eg forgive function

**Comment by mrSkortch** [comment]
Added via commit: https://github.com/mrSkortch/DCS-SLmod/commit/11a12e621e156c4d5a00eda1820a9776e00bd988

Either make a copy of the ExemptClients.lua then delete it, on restart slmod will add the exempt_MOTD entry. It also applies to anyone within exemptAll table. 

Note there is still some heavy logging from the other stuff I added. So might wanna wait until I push all this stuff to the master branch before installing it.
