### ISSUE TITLE
Admin alert message 

### ISSUE THREAD

**Issue by Enfarda** [mrSkortch/DCS-SLmod#44]
Hello,
just to ask if is normal for command show in chat.
![Capturar](https://user-images.githubusercontent.com/43972918/68076083-5a21ac00-fda8-11e9-9bc9-8df237c0a3bb.PNG)

**Comment by mrSkortch** [comment]
Yep, it defaults the message to display as both a triggered message and a chat message. Mostly because the triggered messages can be overwritten by mission triggers and the point of that command is to make sure absolutely everyone in the server will see it.

**Comment by Enfarda** [comment]
kk tks for tip ^^
