### ISSUE TITLE
Collisions count against players although disabled in config.

### ISSUE THREAD

**Issue by Recoil016** [mrSkortch/DCS-SLmod#52]
We're running into issues on the TTI servers where players get disciplined by the Slmod Autoadmin for sliding into each other on the carrier deck. The things is, "autoAdmin.teamCollisionHit.enabled" and "autoAdmin.teamCollisionKill.enabled" are both set to disabled in the config file. Yet we still have players getting kicked:
`TEAM HIT: Apr 01 08:31:30 {players = {1 = {name  = "censored", ucid = "censored", ip = "censored", id = 6}1 = {name = censored with F/A-18C Lot 20`
`TEAM HIT: Apr 01 08:31:30 {players = {1 = {name  = "censored", ucid = "censored", ip = "censored", id = 6}1 = {name = CVN-74 KMART with F/A-18C Lot 20`
`CHAT: Apr 01 08:32:12 {name  = "[107th] Whither 007", ucid = "censored", ip = "censored", id = 4} said "SLMOD INFO: Player "censored" is getting autokicked back to spectator" to all`
On that note, apparently the formatting of Team Hits/Team Kills in the Chat Log is broken to some extent.

**Comment by Recoil016** [comment]
On further investigation, this appears to be only happening to Hornets, probably because they are not recognized by the isAircraft() function as being an aircraft.

**Comment by Recoil016** [comment]
Adding `acft['F/A-18C Lot 20'] = true` above the isAircraft() function bypasses this and circumvents the issue.

**Comment by mrSkortch** [comment]
Sorry I guess I didn't notice this. What version of slmod?

It should have been fixed in develop build 120: https://github.com/mrSkortch/DCS-SLmod/commit/b2a267e66267c70efd6b36df369e87b5be4897e7

**Comment by Recoil016** [comment]
Yeah, we were using build 119, so I'm assuming this is fixed now.
