### ISSUE TITLE
How to install the mod

### ISSUE THREAD

**Issue by FrancoFazz** [mrSkortch/DCS-SLmod#57]
I apologize for the banality of the question, but I would need to understand how to install the mod.
I think I did it right, but then when the simulation starts it gives me a mistake [string 'scriptman']:1: '=' expected near '<eof>'
Thanks for your help

**Comment by mrSkortch** [comment]
You download the zip from either the master or develop branches. You then copy the scripts folder into X:\Users\<username>\Saved Games\DCS.whatever\Scripts folder. This should result in Scripts\hooks\ having a slmodgameGUI.lua file, there might also be files for tacview or srs in there. Meanwhile Scripts\net will have an slmodv7_5 folder, which has a bunch of files with slmod in its name. And that it. 

When you launch a server it will create an slmod folder and config files in the saved games\DCSWhatever\ folder. It will also modify one game file. You can check your install\Scripts\MissionScripting.lua, if it is larger than 2kb then slmod has modified the file.

**Comment by FrancoFazz** [comment]
thanks very kind
