### ISSUE TITLE
Technical info: Either the DB "api/db/db.json" does not exist, or there is no ["server"] index within it

### ISSUE THREAD

**Issue by webdevbrian** [mrSkortch/DCS-SLmod#67]
Few things here (probably related to the documentation and elaboration on specifics):

1) the `db.json` file exists, however has dummy content in it:
```
{
    "token": {
        "server-1": "server-1 secret token",
        "second-server": "second-server secret token",
        "229th-server": "229th-server secret token"
    }
}
```

What would be useful here is elaboration on the "server" index, which the base file does not reference (seen from this error mention):

`Technical info: Either the DB "api/db/db.json" does not exist, or there is no ["server"] index within it`

2) Elaboration in the tokens.json file (that you need to create based off the example) would probably be useful to indicate what SLSC is, and more specifically the examples you include, how they're pertinent:

```
  "SLSC": {
    "server-1": "server-1 secret token",
    "second-server": "second-server secret token",
    "229th-server": "229th-server secret token"
  },
```

Finally, it should also be noted this will not fire up without the use of `nvm` and specifically node version 8 at the moment.

**Comment by mrSkortch** [comment]
I assume you are talking about this other script https://github.com/Bango1999/SLSC?

I'm not involved with that script at all. However part of its functionality can be done directly with slmod as the latest versions of slmod can save a copy of the stats file in json format.
