### ISSUE TITLE
How to enable SLMOD?

### ISSUE THREAD

**Issue by Handsome1080P** [mrSkortch/DCS-SLmod#71]
the server already load slmod,and the folder already created,but in server nothing show up and the commands not working

**Comment by mrSkortch** [comment]
What version are you using? DCS open beta that added the AH-64 required me to update slmod due to some unknown change. If you aren't using the fixed version 7.5.151 then it will not work in open beta.

**Comment by Handsome1080P** [comment]
> 

Latest release.Need I clone the master?

**Comment by Handsome1080P** [comment]
> > 
> 
> Latest release.Need I clone the master?

OK,I saw the hoxfix.
