### ISSUE TITLE
SLMOD ERROR: unable to load banned clients, malformed number near

### ISSUE THREAD

**Issue by chazzbarramundi** [mrSkortch/DCS-SLmod#74]
2022-04-13 09:19:51.496 INFO    LuaNET: SLMOD ERROR: unable to load banned clients, reason: [string "slmod_banned_ips = ..."]:19: malformed number near '4e62e464308d2e05ad89d1e442060774'

Hi, whenever I need to ban a user with a ID that starts with a number as shown above, it causes SLMOD to error out and not load banned IDs. It stops me from being able to ban players using SLMOD. 

Is there a workaround to this? 

Thanks,

**Comment by mrSkortch** [comment]
Could you PM me the BannedClients.lua file? Sounds like there might be a syntax error. Make sure it is formatted like: 

``["4e62e464308d2e05ad89d1e442060774"] = "User Name",

**Comment by chazzbarramundi** [comment]
Hi, so I've been adding these bans manually after they've been reported. So i haven't been using the -admin controls in SLMOD to ban these users. The format below is a copy of the BannedClients.lua. Thanks!

slmod_banned_ips = 
{
} -- end of slmod_banned_ips


slmod_banned_ucids = 
{

c867781386b6ecd9c43ceb34f368690a,
404a3e199a190725ea177d82d45df691, --perm ban


} -- end of slmod_banned_ucids

**Comment by mrSkortch** [comment]
Yep and that is the problem. It isn't formatted correctly. 

Lua thinks you are referencing a variable with those names and it doesn't like it when one starts as a number and then switches to letters. 

However the table is expecting the key and value to be stored as strings. The correct format would be: 


slmod_banned_ucids =
{
["c867781386b6ecd9c43ceb34f368690a"] = "User Name1",
["404a3e199a190725ea177d82d45df691"] = "User Name2",
}

**Comment by chazzbarramundi** [comment]
Cheers I'll follow that format then in future!
