### ISSUE TITLE
Mission Script Error

### ISSUE THREAD

**Issue by Shadeslayers** [mrSkortch/DCS-SLmod#76]
I've been trying to install the mod on my dedicated server, but after I copy the script file over, I keep getting the following error when starting up the DCS World OpenBeta server.

[String "slmod.sendData()"]:1: attempt to index global 'slmod'
(a nil value)
stack traceback:
[C]: ?
[string 'slmod.sendData()"]:1: in main chunk

I copy and paste the scripts folder into Local Disk (C:) > Users > (username) > Saved Games > DCS.openbeta_server

What am I doing wrong?

**Comment by mrSkortch** [comment]
Right click the server icon when starting it and select "Run As Admin"

**Comment by Shadeslayers** [comment]
Thank you! That solved the issue!
